### ISSUE TITLE
tools/generator-terraform : the `identity` block gets reused when the latest version 2022-12-01 Loadtestservice API has two identity properties

### ISSUE THREAD

**Issue by sinbai** [hashicorp/pandora#1825]
The latest version  2022-12-01 Loadtestservice swagger : https://github.com/Azure/azure-rest-api-specs/blob/30deed618795ce9e4a549aa16ef349ae2b03785c/specification/loadtestservice/resource-manager/Microsoft.LoadTestService/stable/2022-12-01/loadtestservice.json

Where the first identity is defined in the swagger : https://github.com/Azure/azure-rest-api-specs/blob/30deed618795ce9e4a549aa16ef349ae2b03785c/specification/loadtestservice/resource-manager/Microsoft.LoadTestService/stable/2022-12-01/loadtestservice.json#L620.

Where the second identity is defined in the swagger: https://github.com/Azure/azure-rest-api-specs/blob/30deed618795ce9e4a549aa16ef349ae2b03785c/specification/loadtestservice/resource-manager/Microsoft.LoadTestService/stable/2022-12-01/loadtestservice.json#L697

In the screenshot below, `resource_id` and `type` should belong to the `identity` of the [EncryptionProperties ](https://github.com/Azure/azure-rest-api-specs/blob/30deed618795ce9e4a549aa16ef349ae2b03785c/specification/loadtestservice/resource-manager/Microsoft.LoadTestService/stable/2022-12-01/loadtestservice.json#L693)but not the `identity` properties of the resource. And the `key_url` should be belong the property of  EncryptionProperties.

![image](https://user-images.githubusercontent.com/39109137/201896132-19aef9ac-72e6-4e6e-b8d1-0cbdfca6c6b8.png)

**Comment by wuxu92** [comment]
Because the `EncryptionProperties` block would be flatten to top-level and it overwtites the origin top-level `identity`. It should only flatten the properties that has no name conflict. I may try to fix this later.

https://github.com/hashicorp/pandora/blob/da99b781d227145c55e5b2cc67a073608d7553ec/tools/importer-rest-api-specs/components/schema/processors/model_flatten_properties_into_parent.go#L36-L40
