### ISSUE TITLE
The resource Id of sapLandscapeMonitor missed the part of "/sapLandscapeMonitor/default"

### ISSUE THREAD

**Issue by neil-yechenwei** [hashicorp/pandora#2382]
I found the [resource id](https://github.com/Azure/azure-rest-api-specs/blob/fdf43f2fdacf17bd78c0621df44a5c024b61db82/specification/workloads/resource-manager/Microsoft.Workloads/stable/2023-04-01/monitors.json#L574) of sapLandscapeMonitor is defined as "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Workloads/monitors/{monitorName}/sapLandscapeMonitor/default" in rest api spec. But seems the [resource id](https://github.com/hashicorp/go-azure-sdk/blob/14a9c1dd5764aab7794f17201b62a54744cc71e7/resource-manager/workloads/2023-04-01/saplandscapemonitor/id_monitor.go#L100) in the generated sdk missed part of "/sapLandscapeMonitor/default". Could you take a look this issue? Thanks.

**Comment by tombuildsstuff** [comment]
@neil-yechenwei `/sapLandscapeMonitor/default` is a static segment and not part of the Resource ID, since this is an operation on the Monitor (and likely a 1:1 relationship between the resources), as such this is working as intended.

As such, from a Terraform perspective this likely needs to be embedded within the Monitor resource, rather than being a separate resource.
