### ISSUE TITLE
`generator-go-sdk` feature propose: request option support configuration

### ISSUE THREAD

**Issue by wuxu92** [hashicorp/pandora#2889]
An API Request like 

```
func (c RegistryManagementClient) RegistriesCreateOrUpdate(
	ctx context.Context,
	id RegistryId,
	input RegistryTrackedResource) (result RegistriesCreateOrUpdateOperationResponse, err error) {
```
from [method_registriescreateorupdate.go](https://github.com/hashicorp/go-azure-sdk/blob/2a15fc0581447ae89479c87714cc9b1141c79743/resource-manager/machinelearningservices/2023-04-01/registrymanagement/method_registriescreateorupdate.go#L24C26-L24C26)

can we provide an varadic argument `func (*client.RequestOptions)` to the method so we can configure the behavior to workaround some swagger issues  like https://github.com/Azure/azure-rest-api-specs/issues/25119. This is right a service swagger issue, but with `Options` our sdk can be more flexible and stronger.

 then the new method may look like:

```
type Option func(*clinet.RequestOptions)

func (c RegistryManagementClient) RegistriesCreateOrUpdate(
	ctx context.Context,
	id RegistryId,
	input RegistryTrackedResource,
	options ...Option
) (result RegistriesCreateOrUpdateOperationResponse, err error) {
```

we can call the Option func before build the request:

```
for _, opt := range options {
	option(opts)
}
req, err := c.Client.NewRequest(ctx, opts)
```

the SDK call from azurerm can be:

```
client.RegistriesCreateOrUpdate(ctx, id, input, func (opt *client.RequestOptions) {
	opt.ExpectedStatusCodes = append(opt.ExpectedStatusCodes, http.StatusAccepted)
})
```

**Comment by tombuildsstuff** [comment]
@wuxu92 we already have this functionality, but it's intentionally not in the Go SDK and instead handled within the Importer.

In short, we can add a [Swagger workaround](https://github.com/hashicorp/pandora/tree/main/tools/importer-rest-api-specs/components/parser/dataworkarounds) ([example PR
(https://github.com/hashicorp/pandora/pull/2883)) to extend this operation to support the new status code - however we'll need a PR on the upstream `Azure/azure-rest-api-specs` repository which applies the fix too - as such would you be able to:

1. Send a PR to the `Azure/azure-rest-api-specs` repository adding this new status code
2. Send a PR to this repository, adding a Swagger workaround for this operation

Once that's done, we have both a long term fix (that is, the fix in the Swagger repository) and the short-term fix (in the form of the Workaround) - meaning that users of the SDK don't need to provide these types of overrides.

Each workaround is named `workaround_{service}_{pr_number}.go` - which is why we require a Pull Request rather than an issue on the upstream `Azure/azure-rest-api-specs` repository

**Comment by wuxu92** [comment]
@tombuildsstuff thanks for you quick review! I created a PR to add the workaround.
