### ISSUE TITLE
Data APIV2 - generating the sdk or terraform causes `dial tcp [::1]:8080: connect: connection refused`

### ISSUE THREAD

**Issue by mbfrahry** [hashicorp/pandora#3413]
Consistently hitting an issue when generating the sdk or terraform from data api v2 that errors with `dial tcp [::1]:8080: connect: connection refused`. That error occurs in any of the errors in the following [loop](https://github.com/hashicorp/pandora/blob/main/tools/sdk/services/data.go#L52). 

Rerunning the method that fails fixes the connection refused issue so I'm wondering if it's worth adding retry-able errors to get around this

**Comment by tombuildsstuff** [comment]
@mbfrahry yeah, I'd agree it'd be sensible to use [`hashicorp/go-retryablehttp`](https://github.com/hashicorp/go-retryablehttp#getting-a-stdlib-httpclient-with-retries) (as we do elsewhere) to workaround this in the short-term - although there's an issue here, so I'd suggest we leave this issue open so that we can dig into that as time allows?

**Comment by tombuildsstuff** [comment]
This was fixed recently in https://github.com/hashicorp/pandora/pull/3587
