### ISSUE TITLE
Add new identity property: `DelegatedResources`

### ISSUE THREAD

**Issue by aristosvo** [hashicorp/pandora#3612]
I'm trying to use the [Containers/2023-06-02-preview SDK](https://github.com/hashicorp/pandora/pull/3469) from the hashicorp/go-azure-sdk , but the identity part of cluster contains some brand new property: DelegatedResources

```go
type ManagedClusterIdentity struct {
	DelegatedResources     *map[string]DelegatedResource                `json:"delegatedResources,omitempty"`
	PrincipalId            *string                                      `json:"principalId,omitempty"`
	TenantId               *string                                      `json:"tenantId,omitempty"`
	Type                   *ResourceIdentityType                        `json:"type,omitempty"`
	UserAssignedIdentities *map[string]UserAssignedIdentitiesProperties `json:"userAssignedIdentities,omitempty"`
}
```

This causes a mismatch in the generator, which makes usage of the `github.com/hashicorp/go-azure-helpers/resourcemanager/identity` package impossible

**Comment by tombuildsstuff** [comment]
hey @aristosvo 

Taking a look at the Swagger description for this new field:

> The delegated identity resources assigned to this managed cluster. This can only be set by another Azure Resource Provider, and managed cluster only accept one delegated identity resource. Internal use only.

As such, it appears that this field is intended to be used purely for (MS) internal use, so I'm surprised it's exposed in the API Definitions - but I think from our side what that means is that we should be ignoring this field if it exists when detecting the Identity types, rather than adding support for this field?

Since this field may (or may not) be present and we're already identifying the `identity` Common Types through duck-typing, we should be able to do the same here.

WDYT?

Thanks!

**Comment by aristosvo** [comment]
It is indeed a bit weird that is exposed, although it has landed in the non-preview AKS API specs as well: https://github.com/search?q=repo%3AAzure%2Fazure-rest-api-specs%20DelegatedResources&type=code
