### ISSUE TITLE
`web` - Generation of SDK does not produce `baseClient.GetSourceControl` as  it conflicts with `webapps.GetSourceControl`

### ISSUE THREAD

**Issue by jackofallops** [hashicorp/pandora#3752]
The method on the BaseClient (which is folded into the WebAppsClient) for retrieving the source control token of a given type is not created:
https://github.com/Azure/azure-rest-api-specs/blob/73d1e6522dfdedb795f46cf997921c623011caa6/specification/web/resource-manager/Microsoft.Web/stable/2023-01-01/ResourceProvider.json#L106

The WebAppsClient has a conflicting name which appears to override it: https://github.com/Azure/azure-rest-api-specs/blob/73d1e6522dfdedb795f46cf997921c623011caa6/specification/web/resource-manager/Microsoft.Web/stable/2023-01-01/WebApps.json#L20261

Both functions are required to support the existing service functionality.

**Comment by tombuildsstuff** [comment]
Taking a quick look it appears that we do have this, [but it's located within the `resourceproviders` package](https://github.com/hashicorp/go-azure-sdk/blob/56a3b343d9df340d4d080516d9d561001c20d57b/resource-manager/web/2023-01-01/resourceproviders/method_getsourcecontrol.go#L21) - which maps to the URI:

> /providers/Microsoft.Web/sourceControls/{sourceControlType}

The [method for the other within the `webapps` package](XXX) maps to the second URI:

> /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Web/sites/{name}/sourceControls/web

As such I believe we support both of these?

---

Context:

When parsing a Swagger Operation we first check for any Tags defined against the Operation - and should the Operation ID be prefixed with that, it’s used as the API Resource.

In the event that it’s not (as is the case here) we group them by the name of the Swagger File (in this case `ResourceProviders.json`) - which is why this is located within the `resourceproviders` package, since this is a Resource Provider scoped operation.
