### ISSUE TITLE
Int32 defined in Swagger becoming Int64 in Hashicorp's go SDK

### ISSUE THREAD

**Issue by paulomarquesc** [hashicorp/pandora#4284]
I need to understand why int32 properties defined in swagger are becoming converted to int64 when producing the SDK.

Here is the Swagger definition:

Source: https://github.com/Azure/azure-rest-api-specs/blob/5700885250d8f685a17293e930d98d1c1d72f401/specification/netapp/resource-manager/Microsoft.NetApp/stable/2023-11-01/netapp.json#L7740

![image](https://github.com/hashicorp/pandora/assets/17993275/129c7baf-d4cc-4bdc-891d-d73acc3da919)

Here is what Azure SDK (track2 generates, which matches 100% swagger):

Source: https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/netapp/armnetapp/v7#BackupPolicyProperties 

![image](https://github.com/hashicorp/pandora/assets/17993275/641fdc13-ffc1-42cd-b381-6710f58bbd70)

Here is what Pandora is generating:

Source: https://pkg.go.dev/github.com/hashicorp/go-azure-sdk/resource-manager@v0.20240708.1080555/netapp/2023-11-01/backuppolicy#BackupPolicyProperties.DailyBackupsToKeep

![image](https://github.com/hashicorp/pandora/assets/17993275/4b1a5b6a-5819-4a30-9598-2ea6dfef8ec3)

Why this difference? I'm afraid the 32 bits architecture tests on Terraform repository will fail because I will have to make my model Int64 to match this.

**Comment by manicminer** [comment]
Hi @paulomarquesc, thanks for opening this issue. The decision to use `int64` for all integers was a design choice, to improve developer experience in Terraform providers. It helps to prevent the churn of integer type conversion particularly since Terraform works with 64-bit integers. It will not cause any compiler issues with 32-bit builds, Go will store it as 2 x 32 bit integers and reconstitute any math operations. It will also not cause any issues with marshalling/unmarshalling, and bounds can (and should) be handled by applications (e.g. validation rules in the case of Terraform).
